name: pet_clean
description: "Recibe alertas de mascotas mientras paseas por la calle"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  geolocator: ^11.0.0
  awesome_notifications_core: ^0.9.3
  awesome_notifications: ^0.9.3+1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  flutter_map_animations: ^0.6.0
  lottie: ^3.1.0
  supabase_flutter: ^2.5.1
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_map_geojson: ^1.0.8
  get: ^4.6.6
  flutter_map_cancellable_tile_provider: ^2.0.0
  image_picker: ^1.1.1
  uuid: ^4.4.0
  fc_native_image_resize: ^0.7.0
  connectivity_plus: ^6.0.3
  flutter_launcher_icons: ^0.13.1
  redis: ^4.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "assets/icon/petalert-icon-background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icon/petalert-icon.png" # only available for Android 8.0 devices and above
  image_path: "assets/icon/petalert-icon.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/
    - .env

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
