name: pet_clean
description: "Recibe alertas de mascotas mientras paseas por la calle"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #Geolocalización
  geolocator: ^11.0.0
  latlong2: ^0.9.1

  #Notificaciones
  awesome_notifications_core: ^0.9.3
  awesome_notifications: ^0.9.3+1

  #Mapas
  flutter_map: ^6.1.0
  flutter_map_geojson: ^1.0.8
  flutter_map_animations: ^0.6.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  
  #Bases de datos
  supabase_flutter: ^2.5.1
  redis: ^4.0.0

  #Gestion de estados
  flutter_bloc: ^8.1.5

  #Variables de entorno
  flutter_dotenv: ^5.1.0

  #Imagenes
  image_picker: ^1.1.1
  fc_native_image_resize: ^0.7.0

  #Generador de UUID
  uuid: ^4.4.0

  #Conectividad
  connectivity_plus: ^6.0.3

  #Iconos de la app
  flutter_launcher_icons: ^0.13.1

  #Animaciones
  flutter_animate: ^4.5.0

  #Auxiliares
  lottie: ^3.1.0
  get: ^4.6.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "assets/icon/petalert-icon-background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icon/petalert-icon.png" # only available for Android 8.0 devices and above
  image_path: "assets/icon/petalert-icon.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/
    - .env
